version: '3.8'

services:
    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        restart: unless-stopped
        ports:
            - '7575:7575'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume2/docker/services/homarr/appdata:/appdata
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Etc/UTC
            - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}

    homeassistant:
        container_name: homeassistant
        image: 'ghcr.io/home-assistant/home-assistant:stable'
        volumes:
            - /volume2/docker/services/homeassistant/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        privileged: true
        network_mode: host

networks:
    github_default:
        driver: bridge

volumes:
    homarr-appdata:
