version: '3.8'

services:
    tunnel:
        container_name: cloudflared-tunnel
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: tunnel run
        network_mode: host
        environment:
            - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
        dns:
            - 192.168.4.61
            - 1.1.1.1
networks:
    github_default:
        driver: bridge
