version: '3.8'

services:
    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        restart: unless-stopped
        ports:
            - '7575:7575'
        dns:
            - 192.168.4.61
            - 1.1.1.1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume2/docker/services/homarr/appdata:/appdata
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Etc/UTC
            - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}

    homeassistant:
        container_name: homeassistant
        image: 'ghcr.io/home-assistant/home-assistant:stable'
        volumes:
            - /volume2/docker/services/homeassistant/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        privileged: true
        network_mode: host
        dns:
            - 192.168.4.61
            - 1.1.1.1

    adguardhome:
        container_name: adguard
        image: adguard/adguardhome
        ports:
            - 53:53/tcp # plain dns over tcp
            - 53:53/udp # plain dns over udp
            - 8040:80/tcp # http web interface
            - 3000:3000/tcp # initial setup web interface
        dns:
            - 192.168.4.61
            - 1.1.1.1
        volumes:
            - config:/opt/adguardhome/conf # app configuration
            - work:/opt/adguardhome/work # app working directory

networks:
    github_default:
        driver: bridge
        dns:
            - 192.168.4.61
            - 1.1.1.1

volumes:
    homarr-appdata:
    config:
    work:
