version: '3.8'

services:
    mc:
        container_name: minecraft
        image: itzg/minecraft-server
        environment:
            MEMORY: '4G'
            EULA: 'true'
            TYPE: 'PAPER'
            PLUGINS: |
                https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
                https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        ports:
            - '25565:25565'
            - '19132:19132/udp'
        volumes:
            - minecraft-data:/data

volumes:
    minecraft-data:
