version: '3.8'

services:
    tunnel:
        container_name: cloudflared-tunnel
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: tunnel run
        network_mode: host
        environment:
            - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}

networks:
    github_default:
        driver: bridge
