name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          echo "::set-output name=changed::[\"$(ct list-changed --config .github/ct-lint.yaml)\"]"

      - name: Parse list-changed
        id: set-matrix
        env:
          CHANGED: ${{ steps.list-changed.outputs.changed }}
        run: |
          echo "::set-output name=matrix::$(echo "${CHANGED//\\n/\",\"}")"

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        chart: ${{ fromJson(needs.lint-chart.outputs.matrix) }}
        k8s:
          - "1.25.5"
          - "1.24.9"
          - "1.23.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Helm depdendencies
        env:
          CHART_DIR: ${{ matrix.chart }}
        run: |
          helm dependency update "${CHART_DIR}"
          mkdir tmp
          helm template "${CHART_DIR}" > tmp/combined.yaml

      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform

      - name: Run kubeconform
        if: ${{ matrix.k8s }}
        run: kubeconform -kubernetes-version ${{ matrix.k8s }} tmp/combined.yaml

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeconform-chart
    strategy:
      matrix:
        k8s:
          - v1.25.3
          - v1.24.7
          - v1.23.13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.4.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (install)
        run: ct install --config .github/ct-install.yaml
